name: Angular Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup
      needs: Checkout
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Dependencies
      needs: Setup
      run: npm install

    - name: Build Angular application
      needs: Dependencies
      run: npm run build -- --prod
